version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-gym
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 422003
      MYSQL_DATABASE: gymdb
      MYSQL_USER: lehaitien
      MYSQL_PASSWORD: 422003Tien@
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: minio-gym
    restart: always
    environment:
      MINIO_ROOT_USER: lehaitien
      MINIO_ROOT_PASSWORD: 422003Tien@
      MINIO_DEFAULT_BUCKETS: gym-crm
    command: server --address ":9200" --console-address ":9201" /data
    ports:
      - "9200:9200"  # API MinIO
      - "9201:9201"  # Giao diện Web MinIO
    volumes:
      - minio_data:/data
    networks:
      - backend

  minio-init:
    image: minio/mc
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: ["/bin/sh", "-c", "/app/create-bucket.sh"]
    volumes:
      - ./create-bucket.sh:/app/create-bucket.sh
    networks:
      - backend

volumes:
  mysql_data:
  minio_data:

networks:
  backend:
