server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mysql-14e47e17-lehaitien422003dev-gym.i.aivencloud.com:14838/defaultdb?useSSL=true&requireSSL=true&trustServerCertificate=true
    username: ${DB_MSQL_USERNAME}
    password: ${DB_MSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:mysql://mysql-14e47e17-lehaitien422003dev-gym.i.aivencloud.com:14838/defaultdb?useSSL=true&requireSSL=true&trustServerCertificate=true
    user: ${DB_MSQL_USERNAME}
    password: ${DB_MSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 360000 # in seconds


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

minio:
  url: https://minio-api.lehaitien.site
  accessKey: lehaitien
  secretKey: 422003Tien@
  bucket: gym-crm
