global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'lehaiten422003dev@gmail.com'
  smtp_auth_username: 'lehaiten422003dev@gmail.com'
  smtp_auth_password: 'zgle ldjp dzco amhz'
  smtp_require_tls: true

route:
  receiver: 'email-alert'

receivers:
  - name: 'email-alert'
    email_configs:
      - to: 'lehaiten422003dev@gmail.com'
        send_resolved: true
