groups:
  - name: http_errors.rules
    rules:
      - alert: HighHTTP4xxErrors
        expr: |
          sum by (job, instance, status) (
            increase(http_server_requests_seconds_count{status=~"4.."}[5m])
          ) > 1000
        for: 1m
        labels:
          severity: warning
          category: http_error
        annotations:
          summary: "High HTTP 4xx Errors on {{ $labels.instance }}"
          description: "Tổng số HTTP 4xx errors trên {{ $labels.instance }} vượt quá 1000 trong 5 phút. Status: {{ $labels.status }}"

      - alert: HighHTTP5xxErrors
        expr: |
          sum by (job, instance, status) (
            increase(http_server_requests_seconds_count{status=~"5.."}[5m])
          ) > 1000
        for: 1m
        labels:
          severity: critical
          category: http_error
        annotations:
          summary: "High HTTP 5xx Errors on {{ $labels.instance }}"
          description: "Tổng số HTTP 5xx errors trên {{ $labels.instance }} vượt quá 1000 trong 5 phút. Status: {{ $labels.status }}"

      - alert: HighHTTPErrorRate
        expr: |
          sum by (job, instance) (
            rate(http_server_requests_seconds_count{status=~"4..|5.."}[5m])
          )
          /
          sum by (job, instance) (
            rate(http_server_requests_seconds_count[5m])
          )
          > 0.3
        for: 2m
        labels:
          severity: warning
          category: http_error
        annotations:
          summary: "High HTTP Error Rate on {{ $labels.instance }}"
          description: "Tỷ lệ lỗi HTTP 4xx/5xx trên {{ $labels.instance }} vượt quá 30% trong 5 phút qua."