name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Chạy khi có thay đổi trên nhánh main
  workflow_dispatch:  # Cho phép chạy thủ công trên GitHub Actions

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Đăng nhập Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t lehaitien/gym-crm:latest .

      # Push image lên Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push lehaitien/gym-crm:latest
